name: stepwise_app
description: "A new Flutter project for StepWise."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI/Design
  flex_color_scheme: 8.4.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  glass_kit: ^3.0.0
  lucide_icons: 0.257.0

  # State Management & Architecture
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Networking
  dio: ^5.4.0

  # Audio & Media
  just_audio: ^0.10.5
  audio_waveforms: 2.0.2
  sliding_up_panel: ^2.0.0+1
  just_audio_windows: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
